base_dir: "/Users/saahil/Desktop/Coding_Projects/DL/MicroscopicFungi/archive-2"
batch_size: 32
epochs: 15
learning_rate: 0.0001
height: 224
width: 224
channels: 3
num_folds: 5
patience: 10
seed: 40
log_dir: "./logs"
device: "mps"  # Change to "mps" or "cpu" as needed
